/**
 * routes/documents.js — v0.6
 *
 * Generates project documents on-the-fly from existing DB data.
 * No new tables needed — assembles what the agents already wrote.
 *
 * GET /projects/:id/documents        — list all available docs
 * GET /projects/:id/documents/:type  — get a specific doc as Markdown
 *
 * Document types:
 *   charter          — Project Charter (from intake brief)
 *   execution-plan   — Full execution plan (from phases/milestones/tasks)
 *   risk-register    — All risks with scores and status
 *   decision-log     — All decisions with rationale
 *   retro-report     — Latest retro summary
 *   lessons-learned  — Ship retro summary (complete projects only)
 */

import { Router } from 'express';
import { query } from '../db/pool.js';
import { callClaude } from '../lib/anthropic.js';
import { notFound, badRequest } from '../middleware/errors.js';

const router = Router({ mergeParams: true });

// ── Document assemblers ────────────────────────────────────────────────────────

async function buildCharter(id) {
  const { rows: [p] } = await query(
    `SELECT p.*,
       COALESCE(json_agg(DISTINCT jsonb_build_object('criterion', sc.criterion, 'sort_order', sc.sort_order))
         FILTER (WHERE sc.id IS NOT NULL), '[]') AS success_criteria,
       COALESCE(json_agg(DISTINCT jsonb_build_object('description', si.description, 'in_scope', si.in_scope))
         FILTER (WHERE si.id IS NOT NULL), '[]') AS scope_items
     FROM projects p
     LEFT JOIN success_criteria sc ON sc.project_id = p.id
     LEFT JOIN scope_items si ON si.project_id = p.id
     WHERE p.id = $1 GROUP BY p.id`, [id])

  if (!p) return null

  const inScope  = (p.scope_items ?? []).filter(s => s.in_scope).map(s => `- ${s.description}`).join('\n')
  const outScope = (p.scope_items ?? []).filter(s => !s.in_scope).map(s => `- ${s.description}`).join('\n')
  const criteria = (p.success_criteria ?? [])
    .sort((a, b) => a.sort_order - b.sort_order)
    .map((s, i) => `${i + 1}. ${s.criterion}`).join('\n')

  const date = new Date(p.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })

  return `# Project Charter — ${p.title}

**Generated:** ${date}
**Stage:** ${p.stage?.replace(/_/g, ' ')}
**Confidence:** ${p.confidence_score ?? 'N/A'}/100

---

## Overview

**One-liner:** ${p.one_liner ?? 'Not defined'}

**Project type:** ${p.project_type ?? 'Not specified'}

**Target user:** ${p.target_user ?? 'Not defined'}

**Core problem:** ${p.core_problem ?? 'Not defined'}

---

## Success Criteria

${criteria || '_No success criteria defined yet_'}

---

## Scope

### In scope (v1)
${inScope || '_No scope items defined_'}

### Out of scope (v1)
${outScope || '_Nothing explicitly excluded_'}

---

## Constraints

| Constraint | Value |
|-----------|-------|
| Hours per week | ${p.hours_per_week ?? 'Not set'} |
| Budget | ${p.budget ?? 'Not set'} |
| Planned weeks | ${p.planned_weeks ?? 'Not set'} |
| Methodology | ${p.methodology ?? 'Not set'} |

---

## Project ID

\`${id}\`

_This document was auto-generated by Project OS from your intake conversation._`
}

async function buildExecutionPlan(id) {
  const { rows: phases } = await query(
    `SELECT id, title, goal, sort_order FROM phases WHERE project_id = $1 ORDER BY sort_order`, [id])
  if (!phases.length) return null

  const { rows: milestones } = await query(
    `SELECT m.id, m.phase_id, m.title, m.success_condition, m.estimated_hours, m.completed_at, m.sort_order
     FROM milestones WHERE project_id = $1 ORDER BY sort_order`, [id])

  const { rows: tasks } = await query(
    `SELECT t.milestone_id, t.task_key, t.title, t.description, t.status,
            t.priority, t.estimated_hours, t.actual_hours, t.completed_at
     FROM tasks WHERE project_id = $1 ORDER BY created_at`, [id])

  const { rows: [p] } = await query(
    `SELECT title, methodology, total_estimated_hours, planned_weeks, scope_warning FROM projects WHERE id = $1`, [id])

  const tasksByMs = {}
  for (const t of tasks) {
    if (!tasksByMs[t.milestone_id]) tasksByMs[t.milestone_id] = []
    tasksByMs[t.milestone_id].push(t)
  }
  const msByPhase = {}
  for (const m of milestones) {
    if (!msByPhase[m.phase_id]) msByPhase[m.phase_id] = []
    msByPhase[m.phase_id].push(m)
  }

  const STATUS_EMOJI = { done: '✅', in_progress: '🔄', blocked: '⛔', todo: '⬜' }
  const PRI_LABEL    = { critical: '🔴', high: '🟡', normal: '⚪' }

  let md = `# Execution Plan — ${p?.title ?? 'Project'}\n\n`
  md += `**Methodology:** ${p?.methodology ?? 'Not set'}\n`
  md += `**Total estimated:** ${p?.total_estimated_hours ?? '?'}h over ${p?.planned_weeks ?? '?'} weeks\n`
  if (p?.scope_warning) md += `\n> ⚠️ ${p.scope_warning}\n`
  md += '\n---\n\n'

  for (const phase of phases) {
    md += `## Phase: ${phase.title}\n`
    if (phase.goal) md += `_${phase.goal}_\n\n`

    for (const ms of (msByPhase[phase.id] ?? [])) {
      const done   = ms.completed_at ? '✅ Complete' : '🔄 In progress'
      const msTasks = tasksByMs[ms.id] ?? []
      const doneCount = msTasks.filter(t => t.status === 'done').length
      md += `### Milestone: ${ms.title} ${done}\n`
      if (ms.success_condition) md += `**Done when:** ${ms.success_condition}\n`
      md += `**Progress:** ${doneCount}/${msTasks.length} tasks · ${ms.estimated_hours ?? '?'}h estimated\n\n`
      md += `| Task | Priority | Status | Est. | Actual |\n|------|----------|--------|------|--------|\n`
      for (const t of msTasks) {
        const est  = t.estimated_hours ? `${t.estimated_hours}h` : '—'
        const act  = t.actual_hours    ? `${t.actual_hours}h`    : '—'
        md += `| ${STATUS_EMOJI[t.status] ?? '⬜'} ${t.title} | ${PRI_LABEL[t.priority] ?? '⚪'} ${t.priority} | ${t.status.replace('_', ' ')} | ${est} | ${act} |\n`
      }
      md += '\n'
    }
  }

  md += '\n_This document was auto-generated by Project OS._'
  return md
}

async function buildRiskRegister(id) {
  const { rows: risks } = await query(
    `SELECT description, likelihood, impact, risk_score, status, source_agent, owner, mitigation, created_at
     FROM risk_register WHERE project_id = $1 ORDER BY risk_score DESC, created_at`, [id])

  if (!risks.length) return null

  const open       = risks.filter(r => r.status === 'open' && !r.description?.startsWith('ASSUMPTION:'))
  const assumptions = risks.filter(r => r.description?.startsWith('ASSUMPTION:'))
  const resolved   = risks.filter(r => ['mitigated','accepted','closed'].includes(r.status))

  const riskTable = (rows) => {
    if (!rows.length) return '_None_\n'
    let t = `| Score | Description | Likelihood | Impact | Status | Owner |\n`
    t    += `|-------|-------------|------------|--------|--------|-------|\n`
    for (const r of rows) {
      const desc = r.description.replace(/^ASSUMPTION:\s*/i, '')
      t += `| ${r.risk_score}/9 | ${desc} | ${r.likelihood} | ${r.impact} | ${r.status} | ${r.owner} |\n`
    }
    return t + '\n'
  }

  return `# Risk Register\n\n## Open Risks (${open.length})\n\n${riskTable(open)}## Assumptions (${assumptions.length})\n\n${riskTable(assumptions)}## Resolved (${resolved.length})\n\n${riskTable(resolved)}\n_Auto-generated by Project OS._`
}

async function buildDecisionLog(id) {
  const { rows: decisions } = await query(
    `SELECT decision, rationale, risk_evaluation, outcome, decided_at
     FROM decision_log WHERE project_id = $1 ORDER BY decided_at DESC`, [id])

  if (!decisions.length) return null

  let md = `# Decision Log\n\n`
  for (const d of decisions) {
    const date = new Date(d.decided_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: '2-digit' })
    md += `## ${d.decision}\n`
    md += `**Date:** ${date}\n\n`
    if (d.rationale)       md += `**Rationale:** ${d.rationale}\n\n`
    if (d.risk_evaluation) md += `**Risk evaluation:** ${d.risk_evaluation}\n\n`
    if (d.outcome)         md += `**Outcome:** ${d.outcome}\n\n`
    md += '---\n\n'
  }
  return md + '_Auto-generated by Project OS._'
}

async function buildRetroReport(id) {
  const { rows: retros } = await query(
    `SELECT r.*, m.title AS milestone_title
     FROM retrospectives r
     LEFT JOIN milestones m ON m.id = r.milestone_id
     WHERE r.project_id = $1 ORDER BY r.triggered_at DESC`, [id])

  if (!retros.length) return null

  let md = `# Retrospective Reports\n\n`
  for (const r of retros) {
    const date  = new Date(r.triggered_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    const title = r.retro_type === 'ship_retro'
      ? '🚀 Ship Retrospective'
      : `🏁 Milestone Retro — ${r.milestone_title ?? 'Milestone'}`

    md += `## ${title}\n`
    md += `**Date:** ${date}\n`
    md += `**Tasks:** ${r.tasks_completed ?? '?'}/${r.tasks_planned ?? '?'} completed\n`
    if (r.estimated_hours && r.actual_hours) {
      const variance = (r.actual_hours - r.estimated_hours).toFixed(1)
      md += `**Hours:** ${r.actual_hours}h actual vs ${r.estimated_hours}h estimated (${variance > 0 ? '+' : ''}${variance}h)\n\n`
    }
    if (r.what_worked)           md += `**What was delivered:**\n${r.what_worked}\n\n`
    if (r.what_created_friction) md += `**What created friction:**\n${r.what_created_friction}\n\n`
    if (r.what_would_you_change) md += `**What I'd change:**\n${r.what_would_you_change}\n\n`
    if (r.founder_growth_read)   md += `**Founder growth read:**\n${r.founder_growth_read}\n\n`

    const patterns = Array.isArray(r.patterns_detected) ? r.patterns_detected : JSON.parse(r.patterns_detected ?? '[]')
    if (patterns.length) {
      md += `**Patterns detected:**\n${patterns.map(p => `- ${p}`).join('\n')}\n\n`
    }
    md += '---\n\n'
  }
  return md + '_Auto-generated by Project OS._'
}

// ── Routes ────────────────────────────────────────────────────────────────────

const DOC_TYPES = [
  { id: 'charter',        label: 'Project Charter',    icon: '📋', stage: 'any' },
  { id: 'execution-plan', label: 'Execution Plan',     icon: '📐', stage: 'execution' },
  { id: 'risk-register',  label: 'Risk Register',      icon: '⚑',  stage: 'any' },
  { id: 'decision-log',   label: 'Decision Log',       icon: '◫',  stage: 'any' },
  { id: 'retro-report',   label: 'Retrospective Report', icon: '🔍', stage: 'retro' },
]

// GET /projects/:id/documents — manifest of available docs
router.get('/', async (req, res, next) => {
  try {
    const { id } = req.params
    const { rows: [p] } = await query(`SELECT stage FROM projects WHERE id = $1`, [id])
    if (!p) throw notFound('Project not found')

    const retro_stages = ['milestone_retro', 'ship_retro', 'complete']

    const docs = DOC_TYPES
      .filter(d => {
        if (d.stage === 'any') return true
        if (d.stage === 'execution') return ['awaiting_approval','execution','milestone_retro','ship_retro','complete'].includes(p.stage)
        if (d.stage === 'retro') return retro_stages.includes(p.stage)
        return true
      })
      .map(d => ({ ...d, url: `/projects/${id}/documents/${d.id}` }))

    return res.json({ documents: docs, project_stage: p.stage })
  } catch (err) { next(err) }
})

// GET /projects/:id/documents/generated — list AI-generated documents
router.get('/generated', async (req, res, next) => {
  try {
    const { id } = req.params
    const { rows } = await query(
      `SELECT id, doc_type, title, generated_at, milestone_id
       FROM generated_documents WHERE project_id = $1 ORDER BY generated_at DESC`,
      [id]
    )
    return res.json({ documents: rows })
  } catch (err) { next(err) }
})

// POST /projects/:id/documents/generate — run Claude to produce a persistent AI report
router.post('/generate', async (req, res, next) => {
  try {
    const { id } = req.params
    const { type } = req.body
    if (!type) throw badRequest('type is required (milestone-report | close-report)')

    const allowed = ['milestone-report', 'close-report']
    if (!allowed.includes(type)) throw badRequest(`Unknown type. Allowed: ${allowed.join(', ')}`)

    // Fetch project data
    const { rows: [p] } = await query(
      `SELECT title, stage, one_liner, core_problem, target_user, overall_status,
              momentum_score, total_estimated_hours, planned_weeks
       FROM projects WHERE id = $1`, [id]
    )
    if (!p) throw notFound('Project not found')

    // Fetch tasks summary
    const { rows: tasks } = await query(
      `SELECT t.title, t.status, t.estimated_hours, t.actual_hours, m.title AS milestone
       FROM tasks t JOIN milestones m ON m.id = t.milestone_id
       WHERE t.project_id = $1 ORDER BY m.sort_order, t.created_at`, [id]
    )

    // Fetch recent retros
    const { rows: retros } = await query(
      `SELECT retro_type, what_worked, what_created_friction, what_would_you_change,
              tasks_completed, tasks_planned, estimated_hours, actual_hours, triggered_at
       FROM retrospectives WHERE project_id = $1 ORDER BY triggered_at DESC LIMIT 3`, [id]
    )

    // Fetch open risks
    const { rows: risks } = await query(
      `SELECT description, risk_score, likelihood, impact, status
       FROM risk_register WHERE project_id = $1 AND status = 'open' ORDER BY risk_score DESC`, [id]
    )

    const taskSummary = tasks.map(t =>
      `- [${t.status}] ${t.title} (${t.estimated_hours ?? '?'}h est${t.actual_hours ? `, ${t.actual_hours}h actual` : ''}) — ${t.milestone}`
    ).join('\n')

    const retroSummary = retros.map(r => {
      const date = new Date(r.triggered_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: '2-digit' })
      return `**${r.retro_type} (${date}):** Tasks: ${r.tasks_completed ?? '?'}/${r.tasks_planned ?? '?'}. ${r.what_worked ?? ''}`
    }).join('\n')

    const riskSummary = risks.map(r => `- [${r.risk_score}/9] ${r.description}`).join('\n')

    let docTitle, systemPrompt, userMessage

    if (type === 'milestone-report') {
      docTitle = `Milestone Report — ${p.title}`
      systemPrompt = `You are a project intelligence agent. Write a concise milestone progress report for a solo founder's project. Be direct, data-driven, and honest. Use markdown. Focus on what matters.`
      userMessage = `Write a milestone progress report for: **${p.title}**

Project: ${p.one_liner ?? 'No description'}
Stage: ${p.stage} | Status: ${p.overall_status} | Momentum: ${p.momentum_score ?? 'N/A'}/100

**Task progress:**
${taskSummary || 'No tasks yet'}

**Recent retrospectives:**
${retroSummary || 'No retros yet'}

**Open risks:**
${riskSummary || 'No open risks'}

Format as:
## Current Status
## What's Been Delivered
## Open Issues & Risks
## Next Priorities
## Founder Notes`
    } else {
      docTitle = `Project Close Report — ${p.title}`
      systemPrompt = `You are a project intelligence agent. Write a final project close report for a solo founder. Be honest, specific, and forward-looking. This is a permanent record. Use markdown.`
      userMessage = `Write a final close report for: **${p.title}**

Project: ${p.one_liner ?? 'No description'}
Core problem solved: ${p.core_problem ?? 'Not stated'}
Target user: ${p.target_user ?? 'Not stated'}
Stage: ${p.stage} | Final status: ${p.overall_status} | Momentum: ${p.momentum_score ?? 'N/A'}/100

**All tasks:**
${taskSummary || 'No tasks'}

**Retrospectives:**
${retroSummary || 'No retros recorded'}

**Risks encountered:**
${riskSummary || 'No risks logged'}

Format as:
## Project Summary
## What We Shipped
## What We Learned
## What Slowed Us Down
## v2 / Future Opportunities
## Final Founder Score (1–10 with honest rationale)`
    }

    const { text } = await callClaude({
      system: systemPrompt,
      messages: [{ role: 'user', content: userMessage }],
      max_tokens: 4096,
    })

    const { rows: [doc] } = await query(
      `INSERT INTO generated_documents (project_id, doc_type, title, content)
       VALUES ($1, $2, $3, $4) RETURNING *`,
      [id, type, docTitle, text]
    )

    return res.status(201).json({ document: doc })
  } catch (err) { next(err) }
})

// GET /projects/:id/documents/:type — get doc content as Markdown
router.get('/:type', async (req, res, next) => {
  try {
    const { id, type } = req.params
    const { rows: [p] } = await query(`SELECT id FROM projects WHERE id = $1`, [id])
    if (!p) throw notFound('Project not found')

    let content = null
    switch (type) {
      case 'charter':        content = await buildCharter(id);       break
      case 'execution-plan': content = await buildExecutionPlan(id); break
      case 'risk-register':  content = await buildRiskRegister(id);  break
      case 'decision-log':   content = await buildDecisionLog(id);   break
      case 'retro-report':   content = await buildRetroReport(id);   break
      default: throw badRequest(`Unknown document type: ${type}`)
    }

    if (!content) return res.json({ content: null, message: 'No data available yet for this document' })
    return res.json({ content, type, generated_at: new Date().toISOString() })
  } catch (err) { next(err) }
})

export default router
