/**
 * routes/transitions.js
 *
 * Stage transition endpoint — called by the frontend when:
 *   1. User clicks "Run milestone retro" → triggers milestone_retro stage
 *   2. All milestones done → triggers ship_retro stage
 *   3. Retro complete → project advances to complete automatically
 *
 * Also handles AGENT INTRO MESSAGES — the first message in a new stage
 * is generated by the agent and stored, so the chat is never blank.
 *
 * POST /projects/:id/transition
 * Body: { to_stage: "milestone_retro" | "ship_retro" | "execution" }
 */

import { Router } from 'express';
import { findProjectById, findProjectState, updateProjectStage } from '../db/projects.queries.js';
import { appendMessage, getHistory } from '../db/conversations.queries.js';
import { callClaude } from '../lib/anthropic.js';
import { notFound, badRequest } from '../middleware/errors.js';

const router = Router({ mergeParams: true });

// ── Agent intro messages — what each agent says when a stage begins ───────────

async function generateAgentIntro(project, state, toStage) {
  const VALID_STAGES = ['execution', 'milestone_retro', 'ship_retro']
  if (!VALID_STAGES.includes(toStage)) return null

  const agent = toStage === 'execution' ? 'execution' : 'retro'

  // Build a contextual intro prompt
  let introPrompt = ''

  if (toStage === 'execution') {
    const allTasks = (state?.phases ?? []).flatMap(p => p.milestones ?? []).flatMap(m => m.tasks ?? [])
    const total    = allTasks.length
    const phases   = (state?.phases ?? []).length

    introPrompt = `You are the Execution Agent for a solo founder's AI Project OS. 
The execution plan for "${project.title}" has just been approved by the founder.

Project stats:
- ${total} tasks across ${phases} phase(s)
- Methodology: ${project.methodology ?? 'not specified'}
- ${project.hours_per_week ?? '?'}h/week available
- ${project.planned_weeks ?? '?'} weeks planned

Write a brief, warm intro message (3-4 sentences max) that:
1. Acknowledges the plan is approved and work can begin
2. Explains what daily check-ins will look like (they tell you what they worked on, you update the board)
3. Asks them one direct question: what are they planning to work on FIRST?

Be direct and energetic. No fluff. End with the question.`
  }

  if (toStage === 'milestone_retro') {
    const milestones = (state?.phases ?? []).flatMap(p => p.milestones ?? [])
    const readyMs    = milestones.find(m =>
      !m.completed_at &&
      (m.tasks ?? []).length > 0 &&
      (m.tasks ?? []).every(t => t.status === 'done')
    )
    const msName = readyMs?.title ?? 'the milestone'
    const tasks  = readyMs?.tasks ?? []
    const done   = tasks.filter(t => t.status === 'done').length

    introPrompt = `You are the Retro Agent for a solo founder's AI Project OS.
The founder has completed all ${done} tasks in milestone: "${msName}"

Write a single-sentence acknowledgement of the milestone completion, then immediately ask:
"What did you actually deliver in '${msName}'? Walk me through it — what's working and testable right now?"

That is your ENTIRE response. No preamble. No explanation of what a retro is. Just the one-sentence celebration and the first question.`
  }

  if (toStage === 'ship_retro') {
    const allTasks = (state?.phases ?? []).flatMap(p => p.milestones ?? []).flatMap(m => m.tasks ?? [])
    const done     = allTasks.filter(t => t.status === 'done').length
    const total    = allTasks.length

    introPrompt = `You are the Retro Agent for a solo founder's AI Project OS.
The founder has completed all ${done} tasks across the entire project "${project.title}". This is the ship retro.

Write two sentences: first celebrate that they shipped (be specific about the project name and task count), then immediately ask:
"Walk me through what you actually built — what does a user get when they use ${project.title} today?"

That is your ENTIRE response. Warm, direct, specific. No explanation of what a ship retro is.`
  }

  try {
    const { text } = await callClaude({
      system: 'You generate concise, contextual agent intro messages for a PM tool. Be warm and direct. Never be generic.',
      messages: [{ role: 'user', content: introPrompt }],
      max_tokens: 300,
    })
    return { agent, text }
  } catch (e) {
    console.error('[transition] intro generation failed:', e.message)
    return null
  }
}

// ── POST /projects/:id/transition ─────────────────────────────────────────────

router.post('/', async (req, res, next) => {
  try {
    const { id }      = req.params
    const { to_stage } = req.body ?? {}

    if (!to_stage) throw badRequest('to_stage is required')

    const project = await findProjectById(id)
    if (!project) throw notFound('Project not found')

    const state = await findProjectState(id)

    // Advance the stage
    await updateProjectStage(id, to_stage)

    // Generate and store agent intro message
    const intro = await generateAgentIntro(project, state, to_stage)
    if (intro) {
      await appendMessage({
        project_id: id,
        agent:      intro.agent,
        role:       'assistant',
        content:    intro.text,
      })
    }

    const updated = await findProjectById(id)
    const conversation = await getHistory(id, to_stage === 'execution' ? 'execution' : 'retro', 500)

    return res.json({
      project:      updated,
      stage:        to_stage,
      intro:        intro?.text ?? null,
      conversation,
    })
  } catch (err) {
    next(err)
  }
})

export default router
